// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MindCareAi.Infrastructure.Data;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace MindCareAi.Migrations
{
    [DbContext(typeof(MindCareContext))]
    [Migration("20251120053753_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("RM556934")
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("SEQ_ACOMPANHAMENTO_GS", "RM556934")
                .StartsAt(11L);

            modelBuilder.HasSequence<int>("SEQ_EMPRESA_GS", "RM556934")
                .StartsAt(11L);

            modelBuilder.HasSequence<int>("SEQ_ENCAMINHAMENTO_GS", "RM556934")
                .StartsAt(11L);

            modelBuilder.HasSequence<int>("SEQ_PROFISSIONAL_GS", "RM556934")
                .StartsAt(11L);

            modelBuilder.HasSequence<int>("SEQ_TRIAGEM_GS", "RM556934")
                .StartsAt(11L);

            modelBuilder.HasSequence<int>("SEQ_USUARIO_GS", "RM556934")
                .StartsAt(11L);

            modelBuilder.Entity("MindCareAi.Domain.Entities.Acompanhamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("\"RM556934\".\"SEQ_ACOMPANHAMENTO_GS\".NEXTVAL");

                    b.Property<string>("AnexoUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(400)
                        .HasColumnType("NVARCHAR2(400)")
                        .HasDefaultValue("N/A")
                        .HasColumnName("ANEXO_URL");

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_EVENTO");

                    b.Property<string>("Descricao")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESCRICAO");

                    b.Property<int>("EncaminhamentoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ENCAMINHAMENTO_ID");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TIPO_EVENTO");

                    b.HasKey("Id")
                        .HasName("ACOMPANHAMENTO_PK");

                    b.HasIndex("EncaminhamentoId");

                    b.ToTable("ACOMPANHAMENTO", "RM556934");
                });

            modelBuilder.Entity("MindCareAi.Domain.Entities.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("\"RM556934\".\"SEQ_EMPRESA_GS\".NEXTVAL");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)")
                        .HasColumnName("CNPJ");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)")
                        .HasColumnName("NOME");

                    b.Property<string>("PlanoSaude")
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)")
                        .HasColumnName("PLANO_SAUDE");

                    b.HasKey("Id")
                        .HasName("EMPRESA_PK");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("EMPRESA_CNPJ_UN");

                    b.ToTable("EMPRESA", "RM556934");
                });

            modelBuilder.Entity("MindCareAi.Domain.Entities.Encaminhamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("\"RM556934\".\"SEQ_ENCAMINHAMENTO_GS\".NEXTVAL");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasDefaultValue("N/A")
                        .HasColumnName("ESPECIALIDADE");

                    b.Property<string>("Exame")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)")
                        .HasDefaultValue("N/A")
                        .HasColumnName("EXAME");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(400)
                        .HasColumnType("NVARCHAR2(400)")
                        .HasDefaultValue("N/A")
                        .HasColumnName("OBSERVACAO");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasDefaultValue("MEDIA")
                        .HasColumnName("PRIORIDADE");

                    b.Property<int?>("ProfissionalId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PROFISSIONAL_ID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasDefaultValue("PENDENTE")
                        .HasColumnName("STATUS");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TIPO");

                    b.Property<int>("TriagemId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TRIAGEM_ID");

                    b.HasKey("Id")
                        .HasName("ENCAMINHAMENTO_PK");

                    b.HasIndex("ProfissionalId");

                    b.HasIndex("TriagemId");

                    b.ToTable("ENCAMINHAMENTO", "RM556934");
                });

            modelBuilder.Entity("MindCareAi.Domain.Entities.Profissional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("\"RM556934\".\"SEQ_PROFISSIONAL_GS\".NEXTVAL");

                    b.Property<string>("Contato")
                        .HasMaxLength(160)
                        .HasColumnType("NVARCHAR2(160)")
                        .HasColumnName("CONTATO");

                    b.Property<string>("Convenio")
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)")
                        .HasColumnName("CONVENIO");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("ESPECIALIDADE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.HasKey("Id")
                        .HasName("PROFISSIONAL_PK");

                    b.ToTable("PROFISSIONAL", "RM556934");
                });

            modelBuilder.Entity("MindCareAi.Domain.Entities.Triagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("\"RM556934\".\"SEQ_TRIAGEM_GS\".NEXTVAL");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_HORA");

                    b.Property<string>("Relato")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("RELATO");

                    b.Property<string>("Risco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("RISCO");

                    b.Property<string>("Sugestao")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SUGESTAO");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USUARIO_ID");

                    b.HasKey("Id")
                        .HasName("TRIAGEM_PK");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TRIAGEM", "RM556934");
                });

            modelBuilder.Entity("MindCareAi.Domain.Entities.UsuarioSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("\"RM556934\".\"SEQ_USUARIO_GS\".NEXTVAL");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("EMAIL");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EMPRESA_ID");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("SENHA");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TIPO");

                    b.HasKey("Id")
                        .HasName("USUARIO_PK");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("USUARIO_EMAIL_UN");

                    b.HasIndex("EmpresaId");

                    b.ToTable("USUARIO_SISTEMA", "RM556934");
                });

            modelBuilder.Entity("MindCareAi.Domain.Entities.Acompanhamento", b =>
                {
                    b.HasOne("MindCareAi.Domain.Entities.Encaminhamento", "Encaminhamento")
                        .WithMany("Acompanhamentos")
                        .HasForeignKey("EncaminhamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ACOMPANHAMENTO_ENCAMINHAMENTO_FK");

                    b.Navigation("Encaminhamento");
                });

            modelBuilder.Entity("MindCareAi.Domain.Entities.Encaminhamento", b =>
                {
                    b.HasOne("MindCareAi.Domain.Entities.Profissional", "Profissional")
                        .WithMany("Encaminhamentos")
                        .HasForeignKey("ProfissionalId")
                        .HasConstraintName("ENCAMINHAMENTO_PROFISSIONAL_FK");

                    b.HasOne("MindCareAi.Domain.Entities.Triagem", "Triagem")
                        .WithMany("Encaminhamentos")
                        .HasForeignKey("TriagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ENCAMINHAMENTO_TRIAGEM_FK");

                    b.Navigation("Profissional");

                    b.Navigation("Triagem");
                });

            modelBuilder.Entity("MindCareAi.Domain.Entities.Triagem", b =>
                {
                    b.HasOne("MindCareAi.Domain.Entities.UsuarioSistema", "Usuario")
                        .WithMany("Triagens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("TRIAGEM_USUARIO_FK");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MindCareAi.Domain.Entities.UsuarioSistema", b =>
                {
                    b.HasOne("MindCareAi.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Usuarios")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("USUARIO_EMPRESA_FK");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("MindCareAi.Domain.Entities.Empresa", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("MindCareAi.Domain.Entities.Encaminhamento", b =>
                {
                    b.Navigation("Acompanhamentos");
                });

            modelBuilder.Entity("MindCareAi.Domain.Entities.Profissional", b =>
                {
                    b.Navigation("Encaminhamentos");
                });

            modelBuilder.Entity("MindCareAi.Domain.Entities.Triagem", b =>
                {
                    b.Navigation("Encaminhamentos");
                });

            modelBuilder.Entity("MindCareAi.Domain.Entities.UsuarioSistema", b =>
                {
                    b.Navigation("Triagens");
                });
#pragma warning restore 612, 618
        }
    }
}
